# Generated by Django 4.2.11 on 2024-05-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Single',
        ),
    ]
