# Generated by Django 4.2.11 on 2024-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_rename_worker_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='single',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
