# Generated by Django 4.2.11 on 2024-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0003_single_is_active_single_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
