# Generated by Django 4.2.11 on 2024-05-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laststock', models.IntegerField(default=0)),
                ('present', models.IntegerField(default=0)),
                ('consumed', models.IntegerField(default=0)),
                ('entered', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('incomespent', models.FloatField(default=0)),
                ('incomegained', models.FloatField(default=0)),
                ('expenditures', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.item')),
            ],
        ),
    ]
