# Generated by Django 4.2.11 on 2024-06-17 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_worker_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemreport',
            old_name='entered',
            new_name='addedstock',
        ),
        migrations.RenameField(
            model_name='itemreport',
            old_name='present',
            new_name='currentstock',
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
