# Generated by Django 4.2.11 on 2024-06-17 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_branch_manager_alter_manager_groups_and_more'),
        ('worker', '0003_rename_entered_itemreport_addedstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreport',
            name='expenditures',
        ),
        migrations.CreateModel(
            name='DailyExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expenditure', models.FloatField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.branch')),
            ],
            options={
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
