# Generated by Django 4.2.11 on 2024-05-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_worker_first_name_alter_worker_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
    ]
