# Generated by Django 4.2.11 on 2024-06-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
