# Generated by Django 4.2.11 on 2024-05-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='branch',
        ),
    ]
