# Generated by Django 4.2.11 on 2024-05-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_worker_alter_item_worker'),
        ('manager', '0003_manager_remove_dailyreport_worker_delete_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
